services:
  - type: web
    name: link-collector-bot
    env: python
    region: frankfurt
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: ALLOWED_USER_IDS
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 10
    autoDeploy: true
    branch: main
    plan: starter
